services:
  _defaults:
    autowire: true
    autoconfigure: true

  # 明确注册服务以确保在测试环境中正确工作
  Tourze\IdcardManageBundle\Service\IdcardServiceImpl:
    public: true
    tags: ['tourze.idcard_service']

  # 接口别名，指向实现类
  Tourze\IdcardManageBundle\Service\IdcardService:
    alias: Tourze\IdcardManageBundle\Service\IdcardServiceImpl
    public: true

  # CRUD控制器
  Tourze\IdcardManageBundle\Controller\Admin\IdcardValidationLogCrudController:
    public: true
    tags: ['controller.service_arguments']

  # AdminMenu服务
  Tourze\IdcardManageBundle\Service\AdminMenu:
    public: true
    tags: ['tourze.admin_menu_provider']

  # Repository
  Tourze\IdcardManageBundle\Repository\IdcardValidationLogRepository:
    public: true
    tags: ['doctrine.repository_service']